travis:
  secure:
    BINSTAR_TOKEN: SGr74vGtu1o/t6XCVU6N0lQEyZp1zXM9wy1G5Ck0ZUb+QcaFlcQi4hsRel5JETTTBMtvuqDTZjSTIckx9oGCKNCVZBoz7HLZs9qf+iJYEtYIywGk351A3DI78ThQR2zCME7oxwDoaZm7ZajrhYqIEulQNuph5E2hI+aBnnzaeGmV9c1Z7TU5h+9ekU0L4VuaQvsUdjghqRgP/6FyTZ0o2nDs7c7O1YqLDOsyL8Xi8A7UPQYCpbcaOXKVQ+B14HKWsx8BXccyFRwiGXzB/DwfWqTZvJwJEH3e5xQBSbfXeKXTd+2TPBAolAEae0D2clR0iM04ko8nZ5N5ZwCq2XZjAo4x7od3nYQsWzGv2PXzqLZPQhGsj8DZ9k2XLFC9MKaclQhWblwaRI5NhQqj+Jyk33rXBffPvp7+PXs2jK9/1sxtL9yTmWk24jTDWY7oB9f2w6K36DsyIoyVYKs1WDI1yYoJqlO0zrvDrxLhXFGyb5xOLKjMP7kV4/C3KvMzkLxtYHhQgPc4mDu9Lh96giXk/gkgqlyay50kxLTe4dM1W1iua1NI2D8sQd0G4D/84EpertXTjQYvLt7bmdU5q2YPWecFflRA0guKUQTqEOmuCgO+oFRsSRDlOBUS2XTyBUajzVyLnHFDxJZvSRkg8ADGdsfUe1XbKS2Lpe2RejDR3RE=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
